version: '3'
services:
  weather-app:
    container_name: weather-container
    image: weather:latest
    ports:
      - "8081:8081"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge